---
root: true

env:
  browser: true
  node: true
  es2021: true

extends:
  - airbnb
  - eslint:recommended
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended

overrides: []

parser: '@typescript-eslint/parser'

parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: "./tsconfig.json"
  tsconfigRootDir: "./"

settings:
  import/resolver:
    typescript: {}

plugins:
  - react
  - jsx-a11y
  - react-hooks
  - '@typescript-eslint'

rules:
  eol-last: 0
  max-len:
    - error
    - 160
    - ignoreComments: true
  indent:
    - error
    - 2
    - SwitchCase: 1
  curly:
    - error
    - "all"
  quotes:
    - error
    - single
    - avoidEscape: true
  semi:
    - error
    - always
  comma-dangle:
    - error
    - arrays: always-multiline
      objects: always-multiline
      imports: always-multiline
      exports: always-multiline
      functions: only-multiline
  no-underscore-dangle: "off"
  operator-linebreak:
    - error
    - after
    - overrides:
        "?": before
        ":": before
  import/extensions:
    - off
  react/react-in-jsx-scope:
    - off
  react/jsx-filename-extension:
    - error
    - extensions:
      - ".js"
      - ".ts"
      - ".jsx"
      - ".tsx"
  react/function-component-definition:
    - error
    - namedComponents: "arrow-function"
  react/jsx-props-no-spreading:
    - error
    - custom: "ignore"
  "@typescript-eslint/no-empty-function":
    - off
  react/destructuring-assignment:
    - off
  react/require-default-props:
    - off
  object-curly-newline:
    - error
    - ImportDeclaration:
        minProperties: 6
